require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Layout/LineLength:
  Max: 144

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/Documentation:
  Enabled: false
